flask_demo/app/__init__.py
from flask import Flask
from extend import db
from celery import Celery
from celeryconfig import broker_url
import celeryconfig
celery = Celery(__name__, broker=broker_url)


def creat_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config_name)
    register_celery(app)
    db.init_app(app)
    from .account import account as account_buleprint
    from .book import book as book_buleprint
    from .main import main as main_buleprint
    from .test.views import test as test_buleprint
    app.register_blueprint(account_buleprint, url_prefix='/account')
    app.register_blueprint(book_buleprint, url_prefix='/book')
    app.register_blueprint(test_buleprint, url_prefix='/test')
    app.register_blueprint(main_buleprint)
    return app


def register_celery(app):
    celery.config_from_object('celeryconfig')

    class ContextTask(celery.Task):
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)
    celery.Task = ContextTask
    #return celery

flask_demo/app/account/__init__.py
from .views import account

flask_demo/app/account/views.py
# encoding: utf-8
from flask import (session,
                   render_template,
                   url_for,
                   redirect,
                   request,
                   jsonify)

from extend import db
from app.modles import User
from flask import Blueprint


account = Blueprint('account', __name__, template_folder='templates', static_folder='static')


@account.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    login_name = request.form.get('user')
    passwd = request.form.get('password')
    # login_name # 本打算处理不同方式登陆暂不处理，一律按手机
    user = User.query.filter(User.telnumber == login_name, User.password == passwd).first()
    if user:
        session['user_id'] = user.id
        session.permanent = True
        return redirect(url_for('main.index'))
    return render_template('login.html', error3='账号或密码错误')


@account.route('/logout')
def logout():
    # session.pop('user_id')
    # del session('user_id')
    session.clear()
    return redirect(url_for('main.index'))


@account.route('/regist/', methods=['GET', 'POST'])
def regist():
    if request.method == 'GET':
        return render_template('regist.html')

    telnumber = request.form.get('telnumber')
    passwd1 = request.form.get('passwd1')
    passwd2 = request.form.get('passwd2')
    tel = User.query.filter(User.telnumber == telnumber).first()
    error = None
    if tel:
        error = "该号码已注册"
        return render_template('regist.html', error1=error)

    elif passwd1 != passwd2:
        error = "密码不一致"
        return render_template('regist.html', error2=error)

    else:
        user = User(telnumber=telnumber, password=passwd1)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('account.login'))


# todo此处要加是否登陆装饰器,额这里不确定
@account.route('/createvip/<user_id>', methods=['GET'])
def create_vip(user_id):
    user = User.query.filter(User.id == user_id).first()
    print(user)
    if user:
        user.vip = True
        db.session.commit()

    return redirect(url_for('account.userinfo', user_id=user_id))


# todo此处要加是否登陆装饰器
@account.route('/userinfo/<user_id>')
def userinfo(user_id):
    user = User.query.filter(User.id == user_id).first()
    if user:
        data = {
            'id': user.id,
            'name': user.name,
            'passwd': user.password,
            'telnumber': user.telnumber,
            'vip': user.vip,
            'logintime': user.logintime

        }
        return jsonify(data)

    return redirect(url_for('main.index'))

flask_demo/app/book/__init__.py
from .views import book

flask_demo/app/book/views.py
# encoding: utf-8
from flask import render_template, request, jsonify
from extend import db
from app.modles import Book, Category
from flask import Blueprint

book = Blueprint('book', __name__, template_folder='templates', static_folder='static')


@book.route('/', methods=['GET', 'POST'])
def add_book():
    if request.method == 'GET':
        return render_template('addbook.html')
    name = request.form.get('bookname')
    need_vip = request.form.get('need_vip')
    introduce = request.form.get('introduce')
    book_image = request.form.get('book_image')
    category_id1 = request.form.get('category_id1')
    category_id2 = request.form.get('category_id2')

    if name:
        bookitem = Book(name=name, introduce=introduce, book_image=book_image,
                        need_vip=need_vip, category_id=[category_id1,category_id2])
        db.session.add(bookitem)
        db.session.commit()
        return '''<a href="/book">返回</a>'''
    return '名字不能为空aaaaaaa'


@book.route('/addcategory', methods=['GET', 'POST'])
def add_category():
    if request.method == "GET":
        return render_template('category.html')
    name = request.form.get('category_name')
    father = request.form.get('fatherc_id')
    print(name)
    if name:
        categoryitem = Category(name=name, fatherc_id=father)
        db.session.add(categoryitem)
        db.session.commit()
        return '''<a href="/book/addcategory">返回</a>'''
    return "类名不能为空bbbbbbbb"


@book.route('/bkindex')
def bookindex():
    books = Book.query.all()
    print(books)
    books_data = {}
    for item in books:
        books_data[item.id] = [item.name, item.introduce]
    return jsonify(books_data)


@book.route('/cgindex')
def categoryindex():
    categorys = Category.query.all()
    categorys_data = {}
    for item in categorys:
        categorys_data[item.id] = [item.name]
    return jsonify(categorys_data)

flask_demo/app/main/__init__.py
from .views import main

flask_demo/app/main/views.py
# encoding: utf-8
from flask import session, render_template, Blueprint
import time
from app.modles import User
from app.main.task import long
main = Blueprint('main', __name__, template_folder='templates', static_folder='static')


@main.route('/')
def index():
    return render_template('index.html')


@main.context_processor
def user_status():
    user_id = session.get('user_id')
    if user_id:
        user = User.query.filter(User.id == user_id).first()
        if user:
            return {'user': user}
    return {}


@main.route('/long')
def long_io():
    long.delay()
    print('I have waited for 10s')
    return 'I have waited for 10s'

flask_demo/app/templates/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" href="{{ url_for('book.add_book') }}" method="POST">
    <input type="text" name="bookname" placeholder="书名">
    <input type="text" name="introduce" placeholder="介绍">
    <input type="text" name="book_image" placeholder="book_image">
    <input type="text" name="category_id1" placeholder="种类id1">
    <input type="text" name="category_id2" placeholder="种类id2">

    <hr>
    <button class="btn btn-primary" name="1">提交</button>
</form>
<p></p>
<hr>
<p></p>
</body>
</html>

flask_demo/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{% endblock %}-子衿教育</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
          <img class="logo" src="{{ url_for('static',filename='images/ziji.jpg') }}"></img>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{{ url_for('main.index') }}">首页 <span class="sr-only">(current)</span></a></li>
        <li><a href="#">下载APP</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="好书/好文章">
        </div>
        <button type="submit" class="btn btn-default">Go</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

          {% if user %}
              <li><a href="{{ url_for('account.create_vip', user_id = user.id) }}">开通VIP</a></li>
                <li><a href="{{ url_for('account.userinfo', user_id = user.id) }}">{{ user.telnumber }}</a></li>
                <li><a href="{{ url_for('account.logout') }}">注销</a></li>
            {% else %}
              <li><a href="{{ url_for('account.login') }}">开通VIP</a></li>
                <li><a href="{{ url_for('account.login') }}">{{ '登陆' }}</a></li>
                 <li><a href="{{ url_for('account.regist') }}">注册</a></li>
            {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    {% block main %}{% endblock %}
</body>
</html>


flask_demo/app/templates/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>类</title>
</head>
<body>
<form action="" href="{{ url_for('book.add_category') }}" method="POST">
    <input type="text" name="category_name" placeholder="书的种类名">
    <input type="text" name="fatherc_id" placeholder="所属父类">
    <button class="btn btn-primary" name="2">提交</button>
</form>
</body>
</html>

flask_demo/app/templates/index.html
{% extends 'base.html' %}
{% block title %}首页{% endblock %}
{% block main %}
    <table border="0" width="1300px" >
  <tr>
    <th width="200px">分类</th>
    <th >
        <ul class="nav nav-tabs">
              <li role="presentation" class="active" ><a href="#" >年级</a></li>
                <li role="presentation"><a href="#">科目</a></li>
              <li role="presentation"><a href="#">重难点专题</a></li>
              <li role="presentation"><a href="#">经典案例</a></li>
            <li role="presentation"><a href="#">名师辅导</a></li>
            <li role="presentation"><a href="#">优秀作品</a></li>
            <li role="presentation"><a href="#">VIP专区</a></li>
        </ul>
    </th>
  </tr>
  <tr>
    <td>
        <ul class="nav nav-pills nav-stacked">
              <li role="presentation" class="active"><a href="#">一年级</a></li>
              <li role="presentation"><a href="#">二年级</a></li>
              <li role="presentation"><a href="#">三年级</a></li>
        </ul>
    </td>
    <td>
        <ul>
            {% for book in books_data %}
                <p><a href="#">{{ book.name }}:</a>{{ book.introduce }}</p>
            {% endfor %}
            
        </ul>
    </td>
  </tr>
</table>
    <a href="{{ url_for('book.add_book') }}"><h1>加书</h1></a>
    <a href="{{ url_for('book.add_category') }}"><h1>加书类</h1></a>
{% endblock %}

flask_demo/app/templates/login.html
{% extends 'base.html' %}
{% block title %}登陆{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/login.css') }}">
{% endblock %}
{% block main %}

    <form action="" method="POST">
    <div class="form-content" >
        <h3 class="page-title">登陆</h3>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="用户名/手机号/邮箱" name="user">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="{{ error3|default('密码') }}" name="password">
        </div>
        <div class="form-group">
            <button class="btn btn-primary">立即登陆</button>
        </div>
    </div>
    </form>
{% endblock %}

flask_demo/app/templates/regist.html
{% extends 'base.html' %}
{% block title %}注册{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/regist.css') }}">
{% endblock %}

{% block main %}
<form action="" method="POST">
        <div class="form-content" >
            <h3 class="page-title">注册</h3>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="{{ error1|default('手机') }}" name="telnumber">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="{{ error2|default('密码') }}" name="passwd1">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="确认密码" name="passwd2">
            </div>
            <div class="form-group">
                <button class="btn btn-primary" >注册</button>
            </div>

        </div>
    </form>
{% endblock %}